"""create devices table

Revision ID: 1cb8920e52ad
Revises: 
Create Date: 2026-02-01 22:24:48.033799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cb8920e52ad'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('mgmt_ip', sa.String(length=45), nullable=False),
    sa.Column('vendor', sa.String(length=64), nullable=False),
    sa.Column('device_type', sa.String(length=64), nullable=False),
    sa.Column('site', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_device_type'), 'devices', ['device_type'], unique=False)
    op.create_index(op.f('ix_devices_hostname'), 'devices', ['hostname'], unique=False)
    op.create_index(op.f('ix_devices_mgmt_ip'), 'devices', ['mgmt_ip'], unique=True)
    op.create_index(op.f('ix_devices_site'), 'devices', ['site'], unique=False)
    op.create_index(op.f('ix_devices_vendor'), 'devices', ['vendor'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_devices_vendor'), table_name='devices')
    op.drop_index(op.f('ix_devices_site'), table_name='devices')
    op.drop_index(op.f('ix_devices_mgmt_ip'), table_name='devices')
    op.drop_index(op.f('ix_devices_hostname'), table_name='devices')
    op.drop_index(op.f('ix_devices_device_type'), table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###
